parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest

- name: vmname
  values:
    - momo
    - CBS-OnPrem


trigger: none

jobs:
- job: build
  displayName: build
  pool: 
    name: ${{ parameters.vmname }}
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}